#!/bin/bash
# vim: sw=2 et
#
# Copyright 2014, SUSE
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -e

# Make sure the variables we use are not set
SUSE_VERBOSE=
SUSE_LOGFILE=
DO_STATUS=0
DO_UPGRADE=0
DO_REBOOT=0

### Usage

usage () {
    cat <<EOF
`basename $0` [-h|--help] [-v|--verbose] [COMMAND]

The following commands are available:

  status              Display current status of the upgrade
  upgrade             Upgrade SUSE Cloud 4 to SUSE Cloud 5
  reboot-nodes        Reboot all allocated nodes (except Hyper-V nodes
                      and the Administration Server)

If no command is specified, the status command is assumed.
EOF
    exit
}

while test $# -gt 0; do
    case "$1" in
        -h|--help|--usage|-\?) usage ;;
        -v|--verbose) SUSE_VERBOSE=1 ;;
        -*) ;;
        status) DO_STATUS=1 ;;
        upgrade) DO_UPGRADE=1 ;;
        reboot-nodes) DO_REBOOT=1 ;;
        *) echo "Unknown `basename $0` command: $1"; exit 1 ;;
    esac
    shift
done

COUNT_DO=0
test $DO_STATUS -eq 1 && COUNT_DO=$(($COUNT_DO + 1))
test $DO_UPGRADE -eq 1 && COUNT_DO=$(($COUNT_DO + 1))
test $DO_REBOOT -eq 1 && COUNT_DO=$(($COUNT_DO + 1))
if test $COUNT_DO -eq 0; then
  DO_STATUS=1
elif test $COUNT_DO -gt 1; then
  echo "Only one command can be passed."
  exit 1
fi

export SUSE_VERBOSE


### Common loading and checks

SCRIPT_LIBDIR=/usr/lib/suse-cloud-upgrade
if test ! -f "${SCRIPT_LIBDIR}/common"; then
  SCRIPT_LIBDIR="`dirname $0`/lib"
  if test ! -f "${SCRIPT_LIBDIR}/common"; then
    echo "Internal error: cannot find helpers."
    exit 1
  fi
fi

source "${SCRIPT_LIBDIR}/common"

check_crowbar_key_or_fail
suse_cloud_version=$(get_installed_suse_cloud_version)


##### Special commands

if test $DO_STATUS -eq 1; then
  if test -n "$suse_cloud_version"; then
    echo "Currently installed version of SUSE Cloud: SUSE Cloud $suse_cloud_version"
  else
    echo "Currently installed version of SUSE Cloud: unable to detect!"
  fi

  if test "x$suse_cloud_version" == "x5" -a -f "${UPGRADE_DATA_DIR}/post.run"; then
    echo
    echo "Upgrade from SUSE Cloud 4 to SUSE Cloud 5 has been completed on the"
    echo "Administration Server."
    echo
    echo "Additional steps might still be required; please refer to the deployment guide."
  elif test "x$suse_cloud_version" == "x5" -a -f "${UPGRADE_DATA_DIR}/pre.run"; then
    echo
    echo "Upgrade from SUSE Cloud 4 to SUSE Cloud 5 has been started."
    echo
    echo "Packages seem to have been updated on the Administration Server, you can"
    echo "continue the upgrade by calling \"`basename $0` upgrade\"."
  elif test "x$suse_cloud_version" == "x4" -a -f "${UPGRADE_DATA_DIR}/pre.run"; then
    echo
    echo "Upgrade from SUSE Cloud 4 to SUSE Cloud 5 has been started."
    echo
    echo "Please update the packages on the Administration Server, with \"zypper up\"."
  elif test "x$suse_cloud_version" == "x5"; then
    echo
    echo "No upgrade available."
  elif test "x$suse_cloud_version" == "x4"; then
    echo
    echo "Upgrade from SUSE Cloud 4 to SUSE Cloud 5 has not been started."
    echo
    echo "You can start the process by calling \"`basename $0` upgrade\"."
  elif test -n "$suse_cloud_version"; then
    echo
    echo "Unrecognized version of SUSE Cloud."
  fi

  exit 0
fi


if test $DO_REBOOT -eq 1; then
  if ! ask_yes_no_default_no "Do you want to reboot all allocated SUSE Cloud nodes (except Hyper-V nodes and the Administration Server)?"; then
    exit 0
  fi

  if ! "${SCRIPT_LIBDIR}/reboot-nodes"; then
    echo "Failure while rebooting nodes; some nodes might not have been rebooted!"
    exit 1
  fi

  exit 0
fi


##### Rest of the script is for the upgrade process in two steps
if test $DO_UPGRADE -ne 1; then
  die "Internal error: upgrade command was not passed."
fi


### Many checks for weird situations

if test -z "$suse_cloud_version"; then
  echo "Cannot detect an installation of SUSE Cloud. Is this running on the Administration Server?"
  exit 1
fi

if test "$suse_cloud_version" != "4" -a "$suse_cloud_version" != "5"; then
  echo "Can only upgrade from SUSE Cloud 4 to SUSE Cloud 5."
  exit 1
fi

if test "$suse_cloud_version" == "5" -a ! -f "${UPGRADE_DATA_DIR}/pre.run"; then
  echo "SUSE Cloud 5 is already installed, or the upgrade process was not followed!"
  exit 1
fi

if test "$suse_cloud_version" == "4" -a -f "${UPGRADE_DATA_DIR}/pre.run"; then
  echo "First step of the upgrade process was already completed; please update packages on the Administration Server."
  exit 1
fi

if test ! -f "${UPGRADE_DATA_DIR}/pre.run" -a -f "${UPGRADE_DATA_DIR}/post.run"; then
  echo "Second step of the upgrade process was completed before first step!"
  exit 1
fi

if test -f "${UPGRADE_DATA_DIR}/pre.run" -a -f "${UPGRADE_DATA_DIR}/post.run"; then
  echo "SUSE Cloud upgrade seems to have been completed already!"
  exit 0
fi


### Try to do the upgrade!

if test ! -f "${UPGRADE_DATA_DIR}/pre.run"; then
  if ! ask_yes_no_default_no "Do you want to start the SUSE Cloud upgrade?"; then
    exit 0
  fi

  if ! "${SCRIPT_LIBDIR}/suse-cloud-upgrade-4-to-5-pre"; then
    echo "First step of the upgrade failed. Please contact the support."
    exit 1
  fi

  echo
  echo "First step of the upgrade completed!"
  echo "Please update packages on the Administration Server, and then re-run this utility."
elif test ! -f "${UPGRADE_DATA_DIR}/post.run"; then
  if ! ask_yes_no_default_no "Do you want to continue the SUSE Cloud upgrade?"; then
    exit 0
  fi

  if ! "${SCRIPT_LIBDIR}/suse-cloud-upgrade-4-to-5-post"; then
    echo "Second step of the upgrade failed. Please contact the support."
    exit 1
  fi

  echo
  echo "Second step of the upgrade completed!"
  echo "Please refer to the deployment guide for the next steps to complete the upgrade."
fi
