#!/bin/bash
# vim: sw=2 et
#
# Copyright 2014, SUSE
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

UPGRADE_DATA_DIR=/var/lib/crowbar/upgrade/suse-cloud-2.0-to-3


### Output / log handling

use_log() {
  test -n "$SUSE_LOGFILE"
}

if use_log; then
  mkdir -p "`dirname "$SUSE_LOGFILE"`"

  ### based on install-chef-suse.sh

  # Copy stdout to fd 3
  exec 3>&1
  # Create fd 4 for logfile
  exec 4>> "$SUSE_LOGFILE"

  if [ -z "$SUSE_VERBOSE" ]; then
    # Set fd 1 and 2 to logfile
    exec 1>&4 2>&1
  else
    # Set fd 1 and 2 to logfile (and keep stdout too)
    exec 1> >( tee -a /dev/fd/4 ) 2>&1
  fi
  # Send summary fd to original stdout
  exec 6>&3

  echo_log () {
    echo -e === "$(date '+%F %T %z'): $@" >&4
  }

  echo_summary () {
    # Also send summary to logfile
    echo_log $@

    if [ -z "$SUSE_VERBOSE" ]; then
      echo -e $@ >&3
    else
      echo -e === $@ >&3
    fi
  }

  die() {
    # Send empty line & error to logfile
    echo >&4
    echo_log "Error: $@"

    echo >&3
    echo -e "Error: $@" >&3

    exit 1
  }
else
  echo_summary () {
    if [ -z "$SUSE_VERBOSE" ]; then
      echo -e $@
    else
      echo -e === $@
    fi
  }

  die() {
    echo >&2
    echo -e "Error: $@" >&2

    exit 1
  }
fi


### Helpers

ensure_data_dir() {
  mkdir -p "${UPGRADE_DATA_DIR}"
}

check_crowbar_key_or_fail() {
  if test -z "$CROWBAR_KEY"; then
    echo "CROWBAR_KEY environment variable is not set! Has SUSE Cloud been installed?"
    exit 1
  fi
}

get_installed_suse_cloud_version() {
  if test ! -f /etc/products.d/suse-cloud.prod; then
    return ""
  fi

  LANG=C xmllint --stream --pattern "/product/version" --debug /etc/products.d/suse-cloud.prod | grep -A 1 "matches pattern" | grep "#text" | sed 's/.* [0-9] //'
}

ask_yes_no_default_no() {
  echo -n "$1 [y/N] "
  read ANSWER
  test "x$ANSWER" == "xy" -o "x$ANSWER" == "Y"
}

json_edit=/opt/dell/bin/json-edit
parse_node_data=/opt/dell/barclamps/provisioner/updates/parse_node_data
json_read () {
    file="$1" attr="$2"
    if [ "$file" = '-' ]; then
        $parse_node_data -a "$attr"
    elif [ -f "$file" ]; then
        $parse_node_data "$file" -a "$attr"
    fi | sed "s/^[^=]*=//g"
}

get_repo_url_from() {
  repo="$1" file="$2"
  attr_repo="${repo//./\\.}"

  json_read "$file" attributes.provisioner.suse.autoyast.repos.${attr_repo}.url
}
