#!/bin/bash
# vim: sw=2 et
#
# Copyright 2014, SUSE
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

UPGRADE_DATA_DIR=/var/lib/crowbar/upgrade/suse-cloud-3-to-4

prepare_neutron_migration() {

  # Get nodes that have the neutron_server role
  local neutron_servers=$(cat ${UPGRADE_DATA_DIR}/neutron-server.nodes)

  for neutron_server in $neutron_servers; do
    ssh "$neutron_server" 'source /etc/sysconfig/neutron; \
        for i in $NEUTRON_PLUGIN_CONF; do \
          CONF_ARGS="$CONF_ARGS --config-file $i"; \
        done; \
        neutron-db-manage --config-file /etc/neutron/neutron.conf $CONF_ARGS stamp havana'

    scp "`dirname $0`/neutron-icehouse-migration-helper" "${neutron_server}:/var/lib/neutron"
    ssh "$neutron_server" "/var/lib/neutron/neutron-icehouse-migration-helper"

    # We only need to doi this on one node; On a HA-setup, $neutron_servers can
    # have mutltiple entries
    break
  done
}

finish_neutron_migration() {

  # Get nodes that have the neutron_server role
  local neutron_servers=$(cat ${UPGRADE_DATA_DIR}/neutron-server.nodes)

  for neutron_server in $neutron_servers; do
    ssh "$neutron_server" 'source /etc/sysconfig/neutron; \
        for i in $NEUTRON_PLUGIN_CONF; do \
          CONF_ARGS="$CONF_ARGS --config-file $i"; \
        done; \
        neutron-db-manage --config-file /etc/neutron/neutron.conf $CONF_ARGS upgrade head'
    # We only need to do this on one node; On a HA-setup, $neutron_servers can
    # have mutltiple entries
    break
  done
}
