#!/bin/bash
# vim: sw=2 et
#
# Copyright 2014, SUSE
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -e

SUSE_LOGFILE="/var/log/crowbar/upgrade/`basename $0`.log"
source "`dirname $0`/common"


if test ! -f "${UPGRADE_DATA_DIR}/pre.run"; then
  die "upgrade-suse-cloud-4-to-5-pre needs to be run first."
fi

if test -f "${UPGRADE_DATA_DIR}/post.run"; then
  die "This script has already been run."
fi


ensure_data_dir
check_crowbar_key_or_fail
suse_cloud_version=$(get_installed_suse_cloud_version)

if test "x$suse_cloud_version" != "x5"; then
  die "Current installed version of SUSE Cloud is not 5: $suse_cloud_version"
fi


### Restart some services
echo_summary "Restarting required services..."

if test ! -f /etc/chef/amqp_passwd; then
  grep -m1 "^amqp_pass " /etc/chef/server.rb | sed 's/amqp_pass "\([^"]*\)"/\1/g' > /etc/chef/amqp_passwd
  chmod 600 /etc/chef/amqp_passwd
  chown chef.root /etc/chef/amqp_passwd
  sed -i 's:^amqp_pass ".*":amqp_pass File.read("/etc/chef/amqp_passwd").chomp:' /etc/chef/{server,solr}.rb
fi

if test -f /etc/rabbitmq/rabbitmq-env.conf && \
   grep -q ^SERVER_START_ARGS= /etc/rabbitmq/rabbitmq-env.conf && \
   ! grep -q '^SERVER_START_ARGS=.*-rabbit frame_max 0' /etc/rabbitmq/rabbitmq-env.conf; then
  die "SERVER_START_ARGS already defined in /etc/rabbitmq/rabbitmq-env.conf, without \"-rabbit frame_max 0\""
elif ! ( test -f /etc/rabbitmq/rabbitmq-env.conf && \
   grep -q ^SERVER_START_ARGS= /etc/rabbitmq/rabbitmq-env.conf ); then
  echo '# Workaround for bunny version required by chef not supporting frames' >> /etc/rabbitmq/rabbitmq-env.conf
  echo '# http://bugzilla.suse.com/show_bug.cgi?id=910815' >> /etc/rabbitmq/rabbitmq-env.conf
  echo 'SERVER_START_ARGS="-rabbit frame_max 0"' >> /etc/rabbitmq/rabbitmq-env.conf
fi

rcrabbitmq-server start
rccouchdb start
rcchef-solr start
rcchef-expander start
rcchef-server start


### Reinstall the barclamps
echo_summary "Reinstalling barclamps..."

# remove cached crowbar.yml because of crowbar.yml format change; we will
# reinstall all barclamps anyway
rm -f /opt/dell/crowbar_framework/barclamps/*.yml

# order matters because of dependencies!
for barclamp in crowbar deployer dns ipmi logging network ntp provisioner pacemaker \
         database rabbitmq openstack keystone swift ceph glance cinder neutron nova \
         nova_dashboard ; do
    /opt/dell/bin/barclamp_install.rb --rpm $barclamp
done

# optional barclamps if they're present
for barclamp in updater suse-manager-client nfs_client cisco-ucs hyperv heat ceilometer trove tempest ; do
    if test -d /opt/dell/barclamps/$barclamp; then
        /opt/dell/bin/barclamp_install.rb --rpm $barclamp
    fi
done


### Drop roles that are gone
echo_summary "Removing obsolete data..."


### Crowbar can run again
echo_summary "Starting Crowbar..."

# Create the secrets env
if test ! -f /opt/dell/crowbar_framework/config/secrets.env; then
  cat<<EOF > /opt/dell/crowbar_framework/config/secrets.env
export SECRET_KEY_BASE=$(cd /opt/dell/crowbar_framework && RAILS_ENV=production ./bin/rake secret)
EOF
fi

# Remove leftover file from Cloud 3 that breaks the update
for file in /opt/dell/crowbar_framework/db/migrate/*_create_sessions.rb; do
  if ! rpm -qf $file &> null; then
    rm $file
  fi
done

# Make sure that all files are up-to-date
chef-client
rcchef-client start
touch /opt/dell/crowbar_framework/.crowbar-installed-ok

rccrowbar restart


### Updating the repositories in provisioner barclamp
OLD_PROVISIONER_JSON="${UPGRADE_DATA_DIR}/provisioner/default-4.json"
NEW_PROVISIONER_JSON="${UPGRADE_DATA_DIR}/provisioner/default-5.json"
ETC_PROVISIONER_JSON="/etc/crowbar/provisioner.json"
if test -f "$ETC_PROVISIONER_JSON"; then
  if test -n "`json_read "$ETC_PROVISIONER_JSON" attributes.provisioner.suse.autoyast.repos`"; then
    echo_summary "Updating repositories in provisioner configuration..."

    # we don't copy $OLD_PROVISIONER_JSON but redownload the json; that's
    # because there might have been a migration script
    crowbar provisioner proposal show default > "$NEW_PROVISIONER_JSON"

    # drop bits about Cloud 4 repos
    for repo in SUSE-Cloud-4-{Pool,Updates}; do
      attr_repo="${repo//./\\.}"
      $json_edit "$NEW_PROVISIONER_JSON" -a "attributes.provisioner.suse.autoyast.repos.suse-11\.3.${attr_repo}" --remove
    done

    # add/update bits about other repos
    for repo in SLE-Cloud SLE-Cloud-PTF SLES11-SP3-{Pool,Updates} SLE11-HAE-SP3-{Pool,Updates} SUSE-Cloud-5-{Pool,Updates}; do
      url="`get_repo_url_from "$repo" "$ETC_PROVISIONER_JSON"`"
      if test -n "$url"; then
        attr_repo="${repo//./\\.}"
        $json_edit "$NEW_PROVISIONER_JSON" -a "attributes.provisioner.suse.autoyast.repos.suse-11\.3.${attr_repo}.url" -v "$url"
      fi
    done

    crowbar provisioner proposal edit default --file "$NEW_PROVISIONER_JSON"
  fi
fi


### Re-sign the PTF repos (as they got moved compared to Cloud 4)
createrepo-cloud-ptf


### Update barclamp proposals to new settings that we prefer
if [ -f "/opt/dell/crowbar_framework/barclamps/pacemaker.yml" ]; then
  # Move pacemaker from multicast to unicast, as it's more solid (Cloud 4 to
  # Cloud 5 only)
  if test "x$suse_cloud_version" != "x5"; then
    die "The pacemaker multicast -> unicast migration is not needed anymore."
  fi

  proposals=$(crowbar pacemaker proposal list)

  if [ "$proposals" != "No current proposals" ]; then
    echo_summary "Migrating pacemaker proposals to Unicast transport..."

    mkdir -p "${UPGRADE_DATA_DIR}/pacemaker"

    for proposal in $proposals; do
      proposal_json="${UPGRADE_DATA_DIR}/pacemaker/${proposal}.json"

      crowbar pacemaker proposal show $proposal > "$proposal_json"

      proposal_transport=$(json_read "$proposal_json" attributes.pacemaker.corosync.transport)
      if [ "$proposal_transport" != "udpu" ]; then
        echo "Migrating pacemaker proposal $proposal to udpu transport..."
        cp -a "$proposal_json" "${proposal_json}.migrated"
        $json_edit "${proposal_json}.migrated" -a "attributes.pacemaker.corosync.transport" -v "udpu"
        # Do not fail upgrade process because of possible validation issues in proposal
        crowbar pacemaker proposal edit $proposal --file "${proposal_json}.migrated" || true
      fi
    done
  fi
fi

### Updating default session timeout in nova_dashboard
proposals=$(crowbar nova_dashboard proposal list)
if [ "$proposals" != "No current proposals" ]; then
  echo_summary "Updating Horizon session timeout due to new Keystone token expiration setting..."

  work_dir="${UPGRADE_DATA_DIR}/nova_dashboard"
  mkdir -p $work_dir

  for proposal in $proposals; do
    proposal_json="$work_dir/${proposal}.json"

    crowbar nova_dashboard proposal show $proposal > "$proposal_json"
    
    cp -a "$proposal_json" "${proposal_json}.migrated"
    # The Horizon session timeout has been reduced to 240 minutes down from 1440 minutes
    # in order to match the Keystone token timeout (14400 seconds = 240 minutes)
    $json_edit "${proposal_json}.migrated" -ra "attributes.nova_dashboard.session_timeout" -v 240
    # Do not fail upgrade process because of possible validation issues in proposal
    crowbar nova_dashboard proposal edit $proposal --file "${proposal_json}.migrated" || true
  done
fi

### Done
touch "${UPGRADE_DATA_DIR}/post.run"
