#!/bin/bash
# vim: sw=2 et
#
# Copyright 2014, SUSE
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -e

SUSE_LOGFILE="/var/log/crowbar/upgrade/`basename $0`.log"
source "`dirname $0`/common"


if test ! -f "${UPGRADE_DATA_DIR}/pre.run"; then
  die "upgrade-suse-cloud-3-to-4-pre needs to be run first."
fi

if test -f "${UPGRADE_DATA_DIR}/post.run"; then
  die "This script has already been run."
fi


ensure_data_dir
check_crowbar_key_or_fail
suse_cloud_version=$(get_installed_suse_cloud_version)

if test "x$suse_cloud_version" != "x4"; then
  die "Current installed version of SUSE Cloud is not 4: $suse_cloud_version"
fi


### Install barclamp new in Cloud 4
zypper --non-interactive install crowbar-barclamp-trove


### Reinstall the barclamps
echo_summary "Reinstalling barclamps..."

# order matters because of dependencies!
for barclamp in crowbar deployer dns ipmi logging network ntp provisioner pacemaker \
         database rabbitmq keystone swift ceph glance cinder neutron nova \
         nova_dashboard openstack trove ; do
    /opt/dell/bin/barclamp_install.rb --rpm $barclamp
done

# optional barclamps if they're present
for barclamp in updater suse-manager-client nfs_client cisco-ucs hyperv heat ceilometer tempest ; do
    if test -d $BARCLAMP_SRC/$i; then
        /opt/dell/bin/barclamp_install.rb --rpm $barclamp
    fi
done


### Drop roles that are gone
echo_summary "Removing obsolete data..."


### Crowbar can run again
echo_summary "Starting Crowbar..."

# Make sure that all files are up-to-date
chef-client
rcchef-client start
touch /opt/dell/crowbar_framework/.crowbar-installed-ok

rccrowbar restart


### Updating the repositories in provisioner barclamp
OLD_PROVISIONER_JSON="${UPGRADE_DATA_DIR}/provisioner/default-3.json"
NEW_PROVISIONER_JSON="${UPGRADE_DATA_DIR}/provisioner/default-4.json"
ETC_PROVISIONER_JSON="/etc/crowbar/provisioner.json"
if test -f "$ETC_PROVISIONER_JSON"; then
  if test -n "`json_read "$ETC_PROVISIONER_JSON" attributes.provisioner.suse.autoyast.repos`"; then
    echo_summary "Updating repositories in provisioner configuration..."

    # we don't copy $OLD_PROVISIONER_JSON but redownload the json; that's
    # because there might have been a migration script
    crowbar provisioner proposal show default > "$NEW_PROVISIONER_JSON"

    # drop bits about Cloud 3 repos
    for repo in SUSE-Cloud-3-{Pool,Updates}; do
      attr_repo="${repo//./\\.}"
      $json_edit "$NEW_PROVISIONER_JSON" -a "attributes.provisioner.suse.autoyast.repos.${attr_repo}" --remove
    done

    # add/update bits about other repos
    for repo in SLE-Cloud SLE-Cloud-PTF SLES11-SP3-{Pool,Updates} SLE11-HAE-SP3-{Pool,Updates} SUSE-Cloud-4-{Pool,Updates}; do
      url="`get_repo_url_from "$repo" "$ETC_PROVISIONER_JSON"`"
      if test -n "$url"; then
        attr_repo="${repo//./\\.}"
        $json_edit "$NEW_PROVISIONER_JSON" -a "attributes.provisioner.suse.autoyast.repos.${attr_repo}.url" -v "$url"
      fi
    done

    crowbar provisioner proposal edit default --file "$NEW_PROVISIONER_JSON"
  fi
fi


### Done
touch "${UPGRADE_DATA_DIR}/post.run"
